# Generated by Django 3.0.2 on 2020-04-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200407_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Great', 'Great'), ('Good', 'Good'), ('Not so good', 'Not so good'), ('Recovering', 'Recovering'), ('Bad', 'Bad')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(default='aMfHxVd46h', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='viRwfL0EJm', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_id',
            field=models.CharField(default='eEyZMaYLvd', max_length=10, primary_key=True, serialize=False),
        ),
    ]
