# Generated by Django 3.0.2 on 2020-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200407_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='notes',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(default='8TnVtX4LrP', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='cCxlxtrJmR', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_id',
            field=models.CharField(default='Ige2cTHKuo', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(blank=True, choices=[('Resolved', 'Resolved'), ('Recovering', 'Recovering'), ('Examination', 'Examination'), ('Critical', 'Critical')], max_length=15, null=True),
        ),
    ]
