# Generated by Django 3.0.2 on 2020-04-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200407_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='next_of_kin_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_of_kin_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.CharField(default='aFSp3rW4wK', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='V8h9mKKPfa', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_id',
            field=models.CharField(default='CrktepnioS', max_length=10, primary_key=True, serialize=False),
        ),
    ]
