# Generated by Django 3.0.2 on 2020-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200407_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='id',
            field=models.CharField(default='ukMtbHnj1W', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.CharField(default='uf7nTbcGlV', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_id',
            field=models.CharField(default='9dED8L0lAx', max_length=10, primary_key=True, serialize=False),
        ),
    ]
