# Generated by Django 3.0.2 on 2020-04-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200407_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.CharField(default='R6dGCpIq8E', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(default='r3SHNxogHP', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_id',
            field=models.CharField(default='ZSeth7m09a', max_length=10, primary_key=True, serialize=False),
        ),
    ]
