# Generated by Django 3.0.2 on 2020-04-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200407_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='history',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.CharField(default='YLHZw2NUua', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.CharField(default='5VEoIxZYHo', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='records',
            name='record_id',
            field=models.CharField(default='sDepcjVDSd', max_length=10, primary_key=True, serialize=False),
        ),
    ]
